### ISSUE TITLE
Conditional debugger breakpoint?

### ISSUE THREAD

**Issue by sepsol** [awto/effectfuljs#31] opened 2023-08-24 21:04 UTC
Is it possible to do something like this in JavaScript:

```diff
for (var i = 0, l = tableNode.table.body.length; i < l; i++) {
+    if (i === 38) debugger;
    // ...
}
```

Or something like this in general in VS Code:

![image](https://github.com/awto/effectfuljs/assets/47871887/1d7619d5-6af0-4521-8fbe-b7a6b7d0b536)

**Comment by awto** [comment] 2023-08-30 16:51
This is supported by this debugger and by the builtin VSCode debugger already.

**Comment by sepsol** [comment] 2023-08-30 18:07
Hmmm, that is weird. For some reason, this is not working for me.

https://github.com/awto/effectfuljs/assets/47871887/ef111100-dcba-40bf-a62f-84e875c4ef9a

Am I doing anything wrong here?

**Comment by awto** [comment] 2023-08-30 19:47
This is strange. Do the usual unconditional breakpoints (or `debugger` statements) work there?

**Comment by sepsol** [comment] 2023-08-30 22:13
@awto Yes sir! In fact, I do demonstrate them in the first 30 seconds of the recording. The second 30 seconds is for Effectful.

**Comment by awto** [comment] 2023-08-30 22:42
It looks like a known problem described here - [interoperating-with-runtimenative-modules](https://marketplace.visualstudio.com/items?itemName=effectful.debugger#interoperating-with-runtimenative-modules). It's likely there is some builtin node streams callback or anything native calling your function, or from some not-instrumented 3rd party JS. 

Could you send the stack trace where it stops in the vscode built-in debugger to be sure?

Unfortunately, if this is the problem, I cannot do much. It's too heavy to implement for me alone, at least now. 

On the positive side, such breakpoints should still work when you run backward or forward but with the already executed and recorded traces.  This works only if you use effectful with time traveling enabled (why would you use effectful without, though). 

So Effectful debugger should still be helpful if you first run the whole program without stopping, but after this, run backward/forward to the interesting points. All breakpoints, including conditional and data breakpoints, should work. Please, let me know if not.

**Comment by sepsol** [comment] 2023-08-31 00:08
I see. Here's the call stack for the built-in debugger along with the file that has the breakpoint and its condition:

![image](https://github.com/awto/effectfuljs/assets/47871887/cb0649cc-ab60-4c7b-9d90-55e100944c4a)

You're right! The "time-travel" feature is exactly what I found interesting about the Effectful debugger.

I tried setting conditional breakpoint inside my `pdfmake` project directory and another one inside the `index.js` that I created for the debugger entry point, right before the program finished execution. Even in this case, the outer breakpoint worked fine while the inner breakpoints didn't work (I couldn't "Reverse" or "Continue"). Although, I was able to manually "Step Back" as you described. But no luck with the inner breakpoints.

**Comment by awto** [comment] 2023-08-31 07:54
This is interesting. I thought the problem was the node streams, but it's not even called from the node streams but the initial constructor. I'll check but I'm not sure when. Could you run it with the following added into launch.json:

```json
            "env": {
                "BABEL_DISABLE_CACHE": "1",
                "EFFECTFUL_DEBUGGER_VERBOSE": "2",
                "EFFECTFUL_VERBOSE": "1",
                "EFFECTFUL_DEBUG_DEBUGGER": "1"
            }
```

and send the output here?

**Comment by sepsol** [comment] 2023-08-31 16:49
Sure thing, I've pasted the logs in [this gist](https://gist.github.com/sepsol/008c839966e4bc2a4929df483b39276b). Thank you for looking into this issue!

**Comment by awto** [comment] 2023-08-31 17:32
Does it also output anything into the Debugger output? I also need some docDefinition and index.js to reproduce this. Could you send them?

**Comment by sepsol** [comment] 2023-08-31 19:04
Sure, here's the [output of the debug console](https://gist.github.com/sepsol/bff3c50c277ada20380f24596b77e9b2).  I also created [this repo](https://github.com/MyBestHomecare/pdfmake-workspace) as a reproducible example.

**Comment by awto** [comment] 2023-09-02 17:02
This should be fixed in 1.4.9. I also implemented stopping in node streams and node events callback. The node streams, however, will need some config. There are details [here](https://marketplace.visualstudio.com/items?itemName=effectful.debugger#debugging-nodejs-streams). 

Please let me know if this works for you, and thanks for the report.

**Comment by sepsol** [comment] 2023-09-04 07:28
Thank you for your efforts on the project! I just tried the update. I can now set unconditional usual breakpoints in the nested `pdfmake` directory, but I can't set conditional breakpoints using builtin VS Code debugger for some reason. The only way for me to set conditional breakpoints is to use the inline `if (i === 3) debugger;` syntax in JavaScript which is not ideal since one has to remember to remove them before committing their changes.

**Comment by awto** [comment] 2023-09-04 15:26
The built-in VS Code debugger isn't from my department. I don't even use it (as an author of Effectful Debugger, it would be a shame if I did). This is something for the VSCode GitHub ticket. Please feel free to reopen this ticket or make a new one if anything needs to be fixed with Effectful Debugger or if you have questions. Thanks!

**Closed** 2023-09-04 15:27 UTC

**Comment by sepsol** [comment] 2023-09-04 16:34
I might have expressed the matter wrong. By "VS Code debugger" I meant the "red breakpoint dots" that you can set on the left side of code lines instead of using the `debugger` keyword in languages like JavaScript (See the [issue description](https://github.com/awto/effectfuljs/issues/31#issue-1865881489) above).

Basically what I'm saying is that the `debugger` now always works anywhere within the project, but for the breakpoints that are set using the "red-dot", only the usual ones work in the files nested inside the `pdfmake/src` directory but the conditional "red dots" don't work. 

The actual builtin VS Code debugger works fine in all cases: usual/conditional, red-dot/debugger.

**Comment by awto** [comment] 2023-09-04 16:47
The same breakpoint as in your example works for me. Except this is line 638 in the file layoutBuilder.js I cloned from your repository. And not 656 like in your example. But I don't expect any problems with this. Could you rerun it with:

```
      "env": {
        "BABEL_DISABLE_CACHE": "1",
        "EFFECTFUL_DEBUGGER_VERBOSE": "2",
        "EFFECTFUL_VERBOSE": "1",
        "EFFECTFUL_DEBUG_DEBUGGER": "1"
      }
```

in launch.json. And send me the whole output from the terminal (not from the Debug tab). On running it should create a terminal called "Effectful Debugger Console".

**Comment by sepsol** [comment] 2023-09-05 16:47
I just tried again and confirmed that the issue has indeed been resolved as you said. Thank you so much for taking the time to fix it; I really appreciate your hard work. Sorry for the confusion.
